[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 10
initialDelay = 30
interval = 30
timeout = 10

[deploy.healthcheck]
path = "/"
initialDelay = 30
interval = 30
timeout = 10
successThreshold = 1
failureThreshold = 3