[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 75"
healthcheckPath = "/"
healthcheckTimeout = 30
initialDelay = 60
interval = 30
timeout = 30

[deploy.healthcheck]
path = "/"
initialDelay = 60
interval = 30
timeout = 30
successThreshold = 1
failureThreshold = 3