[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "python init_db.py && sleep 5 && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
initialDelay = 30
interval = 30
timeout = 10
successThreshold = 1
failureThreshold = 3