[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "python init_db.py && sleep 10 && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10