[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
pythonVersion = "3.11"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 5
initialDelay = 5
interval = 10
timeout = 5
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
initialDelay = 10
interval = 15
timeout = 5
successThreshold = 1
failureThreshold = 3